[tool.poetry]
name = "letsbuildmodels"
version = "0.1.0"
description = "Helper module for letsbuilmodels"
authors = ["Adam Cataldo"]
license = "Apache License Version 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
